apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  labels:
    {{- include "boutiqe-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "boutiqe-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        sidecar.istio.io/inject: "false"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "boutiqe-app.selectorLabels" . | nindent 8 }}
        {{- include "boutiqe-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecret.enabled }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name | default "image-pull-secret" }}
      {{- end }}

      containers:
        {{- range .Values.containers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}

          {{- if .container_port }}
          ports:
            - name: http
              containerPort: {{ .container_port }}
              protocol: TCP
          {{- end }}

          {{- with .env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

