apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-app
  namespace: default
  labels:
    app: recommendation-app
    dev: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: recommendation-app
    spec:
      containers:
        - name: recommendationservice
          image: anamskenneth/recommendationservice:2025-07-24
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
          ports:
            - containerPort: 8080
              name: recommend-port
          volumeMounts:
            - name: localvolume
              mountPath: /etc/localdev
      volumes:
        - name: localvolume
          hostPath:
            path: /etc/app
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: default
spec:
  selector:
    app: recommendation-app
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
