{{- if .Values.imagePullSecret.enabled }}
{{- if .Values.imagePullSecret.dockerConfigJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerConfigJson | b64enc }}
{{- end }}
{{- end }}
