apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-microservices
  namespace: argocd
spec:
  project: microservices-project
  source:
    repoURL: 'https://github.com/kennethchinedu/Chaos-DevOps-SRE-project'
    targetRevision: main                              
    path: boutiqe-app
    # helm:
    #   valueFiles:
    #     - values.yaml                                  
  destination:
    server: 'https://kubernetes.default.svc'          
    namespace: default                                
  syncPolicy:
    automated:
      prune: true          
      selfHeal: true       
    syncOptions:
      - CreateNamespace=true  
