apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: Boutique-project
  namespace: argocd
spec:
  description: Project for all boutique-microservices deployments
  sourceRepos:
    - 'https://github.com/kennethchinedu/Chaos-DevOps-SRE-project'  
  destinations:
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: '!kube-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist: []
