# #Cluster secrets, to switch up clusters, when I move from my local cluster to minikube.

# #Local minikube cluster
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cluster-minikube
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: cluster
# type: Opaque
# stringData:
#   name: minikube
#   server: https://kubernetes.default.svc
#   config: |
#     {
#       "bearerToken": "<service-account-token>",
#       "tlsClientConfig": {
#         "insecure": true
#       }
#     }


# --- 
# #EKS
# apiVersion: v1
# kind: Secret
# metadata:
#   name: cluster-eks
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: cluster
# type: Opaque
# stringData:
#   name: eks
#   server: https://<EKS_CLUSTER_ENDPOINT>
#   config: |
#     {
#       "bearerToken": "<EKS_SERVICE_ACCOUNT_TOKEN>",
#       "tlsClientConfig": {
#         "insecure": false,
#         "caData": "<EKS_CA_DATA>"
#       }
#     }

#Slack Notification secret config

# apiVersion: v1
# kind: Secret
# metadata:
#   name: argocd-notifications-secret
#   namespace: argocd
# stringData:
#   slack-token: "xoxb-your-slack-bot-token"
#   slack-default-channel: "#argocd-alerts" 