apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd.fullname" . }}-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{.Values.deployment.repo}}
  password: {{.Values.deployment.password}}
  username: {{.Values.deployment.username}}
  bearerToken: {{.Values.deployment.bearerToken}}
  project: {{.Values.deployment.project}}
  insecure: "true" # Ignore validity of server's TLS certificate. Defaults to "false"
  forceHttpBasicAuth: "true" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
---