apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  SLACK_TOKEN: "xoxb-1234-your-slack-token"


data:
  triggers: |
    on-sync-failed:
      - description: "Notify when application sync fails"
      - template: app-sync-failed
      - when: app.status.operationState.phase in ['Error','Failed']
    on-health-degraded:
      - description: "Notify when application health is degraded"
      - template: app-health-degraded
      - when: app.status.health.status in ['Degraded','Missing','Suspended']


data:
  subscriptions: |
    - recipients:
        - slack:#deployments-alerts
      triggers:
        - on-sync-failed
        - on-health-degraded
      sources:
        - app: "*"
