apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cart-service-servicemonitor
  annotations:
    meta.helm.sh/release-name: prometheus
  namespace: monitoring
  labels:
    app: cart-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cart-service      
  namespaceSelector:
    matchNames:
      - default              
  endpoints:
    - port: cart-port        
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http