apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: server-app-nodepool
spec:
  # Optional: maintain static number of nodes (can omit if fully dynamic)
  # Template for the nodes Karpenter will provision
  template:
    metadata:
      labels:
        project: "app"
      annotations:
        example.com/owner: "my-team"
    spec:
      # Link to the EC2NodeClass
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: server-app-nodeclass
      # Taints for nodes (prevent pods unless tolerated)
      # taints:
      #   - key: example.com/special-taint
      #     effect: NoSchedule

      # Temporary startup taints
      startupTaints: []

      # Node lifetime settings
      expireAfter: 14h
      terminationGracePeriod: 30m

      # Node requirements
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["c", "m", "r"]
          minValues: 2
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3", "t3a", "t2", "m6i","m5","c6i","c5","r6i","r5"]
          minValues: 5
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["2"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64", "amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]

  # Disruption/consolidation settings
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    budgets:
      - nodes: 10%
      - schedule: "0 9 * * mon-fri"
        duration: 8h
        nodes: "0"

  # Resource limits for the pool
  limits:
    nodes: 4

status:
  conditions:
    - type: Initialized
      status: "False"
      observedGeneration: 1
      lastTransitionTime: "2026-02-01T00:00:00Z"
      reason: NodeClaimNotLaunched
      message: "NodeClaim hasn't succeeded launch"
  nodes: 0
  resources:
    cpu: "0"
    memory: "0"
    ephemeral-storage: "0"
